spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: measurement-route
          uri: lb://measurement-service
          predicates:
            - Path=/api/v1/measurements/**
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"