# ==============================
# DATABASE CONFIG (H2)
# ==============================
spring.datasource.url=jdbc:h2:mem:quantitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==============================
# H2 CONSOLE (for DB testing)
# ==============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==============================
# JWT CONFIG (for token security)
# ==============================
jwt.secret=madhuSecureQuantityMeasurementKey2026abcdef

# ==============================
# GOOGLE OAUTH2 CONFIG
# ==============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email