server:
  port: ${PORT:8081}

spring:
  application:
    name: measurement-service
  datasource:
    url: jdbc:h2:file:./data/measurementdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
