CREATE TABLE IF NOT EXISTS quantity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation VARCHAR(255),
  operand1 DOUBLE,
  operand2 DOUBLE,
  result DOUBLE,
  error BOOLEAN,
  error_message VARCHAR(1000)
);
